{{- $fullName := include "github-runner.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "github-runner.labels" (dict "context" . "component" $fullName "name" $fullName ) | nindent 4 }}
    app.kubernetes.io/version: {{ default .Values.image.tag | quote }}
data:
  gh_token: {{ required ".Values.config.githubToken is required" .Values.config.githubToken | b64enc }}
