{{- if .Values.serviceAccount.create -}}
{{- $fullName := include "github-runner.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "github-runner.serviceAccountName" . }}
  labels:
    {{- include "github-runner.labels" (dict "context" . "component" $fullName "name" $fullName) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
