name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup Environments
        run: |
          # Setup script
          cp ./scripts/edit_index.py /usr/local/bin/edit_index

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add Release
        run: |
          [[ -d .cr-release-packages ]] || exit 0

          git checkout gh-pages
          git pull

          mkdir -p packages

          mv .cr-release-packages/*.tgz packages
          edit_index --path=index.yaml --new_url=packages

          git add *.tgz
          git add index.yaml

          git commit -m "Publish Charts"
          git push
